# Danish translation for nova
# Copyright (c) 2011 Rosetta Contributors and Canonical Ltd 2011
# This file is distributed under the same license as the nova package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: nova\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2011-01-10 11:25-0800\n"
"PO-Revision-Date: 2011-01-15 21:46+0000\n"
"Last-Translator: Soren Hansen <soren@linux2go.dk>\n"
"Language-Team: Danish <da@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2011-01-28 05:20+0000\n"
"X-Generator: Launchpad (build 12177)\n"

#: nova/crypto.py:46
msgid "Filename of root CA"
msgstr ""

#: nova/crypto.py:49
msgid "Filename of private key"
msgstr "Filnavn for privatn√∏gle"

#: nova/crypto.py:51
msgid "Filename of root Certificate Revokation List"
msgstr ""

#: nova/crypto.py:53
msgid "Where we keep our keys"
msgstr ""

#: nova/crypto.py:55
msgid "Where we keep our root CA"
msgstr ""

#: nova/crypto.py:57
msgid "Should we use a CA for each project?"
msgstr ""

#: nova/crypto.py:61
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr ""

#: nova/crypto.py:66
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr ""

#: nova/crypto.py:71
#, python-format
msgid "Subject for certificate for vpns, %s for project, timestamp"
msgstr ""

#: nova/crypto.py:258
#, python-format
msgid "Flags path: %s"
msgstr ""

#: nova/exception.py:33
msgid "Unexpected error while running command."
msgstr ""

#: nova/exception.py:36
#, python-format
msgid ""
"%s\n"
"Command: %s\n"
"Exit code: %s\n"
"Stdout: %r\n"
"Stderr: %r"
msgstr ""

#: nova/exception.py:86
msgid "Uncaught exception"
msgstr ""

#: nova/fakerabbit.py:48
#, python-format
msgid "(%s) publish (key: %s) %s"
msgstr ""

#: nova/fakerabbit.py:53
#, python-format
msgid "Publishing to route %s"
msgstr ""

#: nova/fakerabbit.py:83
#, python-format
msgid "Declaring queue %s"
msgstr ""

#: nova/fakerabbit.py:89
#, python-format
msgid "Declaring exchange %s"
msgstr ""

#: nova/fakerabbit.py:95
#, python-format
msgid "Binding %s to %s with key %s"
msgstr ""

#: nova/fakerabbit.py:120
#, python-format
msgid "Getting from %s: %s"
msgstr ""

#: nova/rpc.py:92
#, python-format
msgid "AMQP server on %s:%d is unreachable. Trying again in %d seconds."
msgstr ""

#: nova/rpc.py:99
#, python-format
msgid "Unable to connect to AMQP server after %d tries. Shutting down."
msgstr ""

#: nova/rpc.py:118
msgid "Reconnected to queue"
msgstr ""

#: nova/rpc.py:125
msgid "Failed to fetch message from queue"
msgstr ""

#: nova/rpc.py:155
#, python-format
msgid "Initing the Adapter Consumer for %s"
msgstr ""

#: nova/rpc.py:170
#, python-format
msgid "received %s"
msgstr ""

#: nova/rpc.py:183
#, python-format
msgid "no method for message: %s"
msgstr ""

#: nova/rpc.py:184
#, python-format
msgid "No method for message: %s"
msgstr ""

#: nova/rpc.py:245
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: nova/rpc.py:286
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: nova/rpc.py:305
msgid "Making asynchronous call..."
msgstr ""

#: nova/rpc.py:308
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: nova/rpc.py:356
#, python-format
msgid "response %s"
msgstr ""

#: nova/rpc.py:365
#, python-format
msgid "topic is %s"
msgstr ""

#: nova/rpc.py:366
#, python-format
msgid "message %s"
msgstr ""

#: nova/service.py:157
#, python-format
msgid "Starting %s node"
msgstr ""

#: nova/service.py:169
msgid "Service killed that has no database entry"
msgstr ""

#: nova/service.py:190
msgid "The service database object disappeared, Recreating it."
msgstr ""

#: nova/service.py:202
msgid "Recovered model server connection!"
msgstr ""

#: nova/service.py:208
msgid "model server went away"
msgstr ""

#: nova/service.py:217 nova/db/sqlalchemy/__init__.py:43
#, python-format
msgid "Data store %s is unreachable. Trying again in %d seconds."
msgstr ""

#: nova/service.py:232 nova/twistd.py:232
#, python-format
msgid "Serving %s"
msgstr ""

#: nova/service.py:234 nova/twistd.py:264
msgid "Full set of FLAGS:"
msgstr ""

#: nova/twistd.py:211
#, python-format
msgid "pidfile %s does not exist. Daemon not running?\n"
msgstr ""

#: nova/twistd.py:268
#, python-format
msgid "Starting %s"
msgstr ""

#: nova/utils.py:53
#, python-format
msgid "Inner Exception: %s"
msgstr ""

#: nova/utils.py:54
#, python-format
msgid "Class %s cannot be found"
msgstr ""

#: nova/utils.py:113
#, python-format
msgid "Fetching %s"
msgstr ""

#: nova/utils.py:125
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: nova/utils.py:138
#, python-format
msgid "Result was %s"
msgstr ""

#: nova/utils.py:171
#, python-format
msgid "debug in callback: %s"
msgstr ""

#: nova/utils.py:176
#, python-format
msgid "Running %s"
msgstr ""

#: nova/utils.py:207
#, python-format
msgid "Couldn't get IP, using 127.0.0.1 %s"
msgstr ""

#: nova/utils.py:289
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: nova/utils.py:300
#, python-format
msgid "backend %s"
msgstr ""

#: nova/api/ec2/__init__.py:133
msgid "Too many failed authentications."
msgstr ""

#: nova/api/ec2/__init__.py:142
#, python-format
msgid ""
"Access key %s has had %d failed authentications and will be locked out for "
"%d minutes."
msgstr ""

#: nova/api/ec2/__init__.py:179 nova/objectstore/handler.py:140
#, python-format
msgid "Authentication Failure: %s"
msgstr ""

#: nova/api/ec2/__init__.py:190
#, python-format
msgid "Authenticated Request For %s:%s)"
msgstr ""

#: nova/api/ec2/__init__.py:227
#, python-format
msgid "action: %s"
msgstr ""

#: nova/api/ec2/__init__.py:229
#, python-format
msgid "arg: %s\t\tval: %s"
msgstr ""

#: nova/api/ec2/__init__.py:301
#, python-format
msgid "Unauthorized request for controller=%s and action=%s"
msgstr ""

#: nova/api/ec2/__init__.py:339
#, python-format
msgid "NotFound raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:342
#, python-format
msgid "ApiError raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:349
#, python-format
msgid "Unexpected error raised: %s"
msgstr ""

#: nova/api/ec2/__init__.py:354
msgid "An unknown error has occurred. Please try your request again."
msgstr ""

#: nova/api/ec2/admin.py:84
#, python-format
msgid "Creating new user: %s"
msgstr ""

#: nova/api/ec2/admin.py:92
#, python-format
msgid "Deleting user: %s"
msgstr ""

#: nova/api/ec2/admin.py:114
#, python-format
msgid "Adding role %s to user %s for project %s"
msgstr ""

#: nova/api/ec2/admin.py:117 nova/auth/manager.py:415
#, python-format
msgid "Adding sitewide role %s to user %s"
msgstr ""

#: nova/api/ec2/admin.py:122
#, python-format
msgid "Removing role %s from user %s for project %s"
msgstr ""

#: nova/api/ec2/admin.py:125 nova/auth/manager.py:441
#, python-format
msgid "Removing sitewide role %s from user %s"
msgstr ""

#: nova/api/ec2/admin.py:129 nova/api/ec2/admin.py:192
msgid "operation must be add or remove"
msgstr ""

#: nova/api/ec2/admin.py:142
#, python-format
msgid "Getting x509 for user: %s on project: %s"
msgstr ""

#: nova/api/ec2/admin.py:159
#, python-format
msgid "Create project %s managed by %s"
msgstr ""

#: nova/api/ec2/admin.py:170
#, python-format
msgid "Delete project: %s"
msgstr ""

#: nova/api/ec2/admin.py:184 nova/auth/manager.py:533
#, python-format
msgid "Adding user %s to project %s"
msgstr ""

#: nova/api/ec2/admin.py:188
#, python-format
msgid "Removing user %s from project %s"
msgstr ""

#: nova/api/ec2/apirequest.py:95
#, python-format
msgid "Unsupported API request: controller = %s,action = %s"
msgstr ""

#: nova/api/ec2/cloud.py:117
#, python-format
msgid "Generating root CA: %s"
msgstr ""

#: nova/api/ec2/cloud.py:277
#, python-format
msgid "Create key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:285
#, python-format
msgid "Delete key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:357
#, python-format
msgid "%s is not a valid ipProtocol"
msgstr ""

#: nova/api/ec2/cloud.py:361
msgid "Invalid port range"
msgstr ""

#: nova/api/ec2/cloud.py:392
#, python-format
msgid "Revoke security group ingress %s"
msgstr ""

#: nova/api/ec2/cloud.py:401 nova/api/ec2/cloud.py:414
msgid "No rule for the specified parameters."
msgstr ""

#: nova/api/ec2/cloud.py:421
#, python-format
msgid "Authorize security group ingress %s"
msgstr ""

#: nova/api/ec2/cloud.py:432
#, python-format
msgid "This rule already exists in group %s"
msgstr ""

#: nova/api/ec2/cloud.py:460
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: nova/api/ec2/cloud.py:463
#, python-format
msgid "group %s already exists"
msgstr ""

#: nova/api/ec2/cloud.py:475
#, python-format
msgid "Delete security group %s"
msgstr ""

#: nova/api/ec2/cloud.py:483 nova/compute/manager.py:452
#, python-format
msgid "Get console output for instance %s"
msgstr ""

#: nova/api/ec2/cloud.py:543
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: nova/api/ec2/cloud.py:567
#, python-format
msgid "Attach volume %s to instacne %s at %s"
msgstr ""

#: nova/api/ec2/cloud.py:579
#, python-format
msgid "Detach volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:686
msgid "Allocate address"
msgstr ""

#: nova/api/ec2/cloud.py:691
#, python-format
msgid "Release address %s"
msgstr ""

#: nova/api/ec2/cloud.py:696
#, python-format
msgid "Associate address %s to instance %s"
msgstr ""

#: nova/api/ec2/cloud.py:703
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: nova/api/ec2/cloud.py:730
msgid "Going to start terminating instances"
msgstr ""

#: nova/api/ec2/cloud.py:738
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: nova/api/ec2/cloud.py:775
#, python-format
msgid "De-registering image %s"
msgstr ""

#: nova/api/ec2/cloud.py:783
#, python-format
msgid "Registered image %s with id %s"
msgstr ""

#: nova/api/ec2/cloud.py:789 nova/api/ec2/cloud.py:804
#, python-format
msgid "attribute not supported: %s"
msgstr ""

#: nova/api/ec2/cloud.py:794
#, python-format
msgid "invalid id: %s"
msgstr ""

#: nova/api/ec2/cloud.py:807
msgid "user or group not specified"
msgstr ""

#: nova/api/ec2/cloud.py:809
msgid "only group \"all\" is supported"
msgstr ""

#: nova/api/ec2/cloud.py:811
msgid "operation_type must be add or remove"
msgstr ""

#: nova/api/ec2/cloud.py:812
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: nova/api/ec2/metadatarequesthandler.py:75
#, python-format
msgid "Failed to get metadata for ip: %s"
msgstr ""

#: nova/api/openstack/__init__.py:70
#, python-format
msgid "Caught error: %s"
msgstr ""

#: nova/api/openstack/__init__.py:86
msgid "Including admin operations in API."
msgstr ""

#: nova/api/openstack/servers.py:184
#, python-format
msgid "Compute.api::lock %s"
msgstr ""

#: nova/api/openstack/servers.py:199
#, python-format
msgid "Compute.api::unlock %s"
msgstr ""

#: nova/api/openstack/servers.py:213
#, python-format
msgid "Compute.api::get_lock %s"
msgstr ""

#: nova/api/openstack/servers.py:224
#, python-format
msgid "Compute.api::pause %s"
msgstr ""

#: nova/api/openstack/servers.py:235
#, python-format
msgid "Compute.api::unpause %s"
msgstr ""

#: nova/api/openstack/servers.py:246
#, python-format
msgid "compute.api::suspend %s"
msgstr ""

#: nova/api/openstack/servers.py:257
#, python-format
msgid "compute.api::resume %s"
msgstr ""

#: nova/auth/dbdriver.py:84
#, python-format
msgid "User %s already exists"
msgstr ""

#: nova/auth/dbdriver.py:106 nova/auth/ldapdriver.py:207
#, python-format
msgid "Project can't be created because manager %s doesn't exist"
msgstr ""

#: nova/auth/dbdriver.py:135 nova/auth/ldapdriver.py:204
#, python-format
msgid "Project can't be created because project %s already exists"
msgstr ""

#: nova/auth/dbdriver.py:157 nova/auth/ldapdriver.py:241
#, python-format
msgid "Project can't be modified because manager %s doesn't exist"
msgstr ""

#: nova/auth/dbdriver.py:245
#, python-format
msgid "User \"%s\" not found"
msgstr ""

#: nova/auth/dbdriver.py:248
#, python-format
msgid "Project \"%s\" not found"
msgstr ""

#: nova/auth/fakeldap.py:33
msgid "Attempted to instantiate singleton"
msgstr ""

#: nova/auth/ldapdriver.py:181
#, python-format
msgid "LDAP object for %s doesn't exist"
msgstr ""

#: nova/auth/ldapdriver.py:218
#, python-format
msgid "Project can't be created because user %s doesn't exist"
msgstr ""

#: nova/auth/ldapdriver.py:478
#, python-format
msgid "User %s is already a member of the group %s"
msgstr ""

#: nova/auth/ldapdriver.py:507
#, python-format
msgid ""
"Attempted to remove the last member of a group. Deleting the group at %s "
"instead."
msgstr ""

#: nova/auth/ldapdriver.py:528
#, python-format
msgid "Group at dn %s doesn't exist"
msgstr ""

#: nova/auth/manager.py:259
#, python-format
msgid "Looking up user: %r"
msgstr ""

#: nova/auth/manager.py:263
#, python-format
msgid "Failed authorization for access key %s"
msgstr ""

#: nova/auth/manager.py:264
#, python-format
msgid "No user found for access key %s"
msgstr ""

#: nova/auth/manager.py:270
#, python-format
msgid "Using project name = user name (%s)"
msgstr ""

#: nova/auth/manager.py:275
#, python-format
msgid "failed authorization: no project named %s (user=%s)"
msgstr ""

#: nova/auth/manager.py:277
#, python-format
msgid "No project called %s could be found"
msgstr ""

#: nova/auth/manager.py:281
#, python-format
msgid "Failed authorization: user %s not admin and not member of project %s"
msgstr ""

#: nova/auth/manager.py:283
#, python-format
msgid "User %s is not a member of project %s"
msgstr ""

#: nova/auth/manager.py:292 nova/auth/manager.py:303
#, python-format
msgid "Invalid signature for user %s"
msgstr ""

#: nova/auth/manager.py:293 nova/auth/manager.py:304
msgid "Signature does not match"
msgstr ""

#: nova/auth/manager.py:374
msgid "Must specify project"
msgstr ""

#: nova/auth/manager.py:408
#, python-format
msgid "The %s role can not be found"
msgstr ""

#: nova/auth/manager.py:410
#, python-format
msgid "The %s role is global only"
msgstr ""

#: nova/auth/manager.py:412
#, python-format
msgid "Adding role %s to user %s in project %s"
msgstr ""

#: nova/auth/manager.py:438
#, python-format
msgid "Removing role %s from user %s on project %s"
msgstr ""

#: nova/auth/manager.py:505
#, python-format
msgid "Created project %s with manager %s"
msgstr ""

#: nova/auth/manager.py:523
#, python-format
msgid "modifying project %s"
msgstr ""

#: nova/auth/manager.py:553
#, python-format
msgid "Remove user %s from project %s"
msgstr ""

#: nova/auth/manager.py:581
#, python-format
msgid "Deleting project %s"
msgstr ""

#: nova/auth/manager.py:637
#, python-format
msgid "Created user %s (admin: %r)"
msgstr ""

#: nova/auth/manager.py:645
#, python-format
msgid "Deleting user %s"
msgstr ""

#: nova/auth/manager.py:655
#, python-format
msgid "Access Key change for user %s"
msgstr ""

#: nova/auth/manager.py:657
#, python-format
msgid "Secret Key change for user %s"
msgstr ""

#: nova/auth/manager.py:659
#, python-format
msgid "Admin status set to %r for user %s"
msgstr ""

#: nova/auth/manager.py:708
#, python-format
msgid "No vpn data for project %s"
msgstr ""

#: nova/cloudpipe/pipelib.py:45
msgid "Template for script to run on cloudpipe instance boot"
msgstr ""

#: nova/cloudpipe/pipelib.py:48
msgid "Network to push into openvpn config"
msgstr ""

#: nova/cloudpipe/pipelib.py:51
msgid "Netmask to push into openvpn config"
msgstr ""

#: nova/cloudpipe/pipelib.py:97
#, python-format
msgid "Launching VPN for %s"
msgstr ""

#: nova/compute/api.py:67
#, python-format
msgid "Instance %d was not found in get_network_topic"
msgstr ""

#: nova/compute/api.py:73
#, python-format
msgid "Instance %d has no host"
msgstr ""

#: nova/compute/api.py:92
#, python-format
msgid "Quota exceeeded for %s, tried to run %s instances"
msgstr ""

#: nova/compute/api.py:94
#, python-format
msgid ""
"Instance quota exceeded. You can only run %s more instances of this type."
msgstr ""

#: nova/compute/api.py:109
msgid "Creating a raw instance"
msgstr ""

#: nova/compute/api.py:156
#, python-format
msgid "Going to run %s instances..."
msgstr ""

#: nova/compute/api.py:180
#, python-format
msgid "Casting to scheduler for %s/%s's instance %s"
msgstr ""

#: nova/compute/api.py:279
#, python-format
msgid "Going to try and terminate %s"
msgstr ""

#: nova/compute/api.py:283
#, python-format
msgid "Instance %d was not found during terminate"
msgstr ""

#: nova/compute/api.py:288
#, python-format
msgid "Instance %d is already being terminated"
msgstr ""

#: nova/compute/api.py:450
#, python-format
msgid "Invalid device specified: %s. Example device: /dev/vdb"
msgstr ""

#: nova/compute/api.py:465
msgid "Volume isn't attached to anything!"
msgstr ""

#: nova/compute/disk.py:71
#, python-format
msgid "Input partition size not evenly divisible by sector size: %d / %d"
msgstr ""

#: nova/compute/disk.py:75
#, python-format
msgid "Bytes for local storage not evenly divisible by sector size: %d / %d"
msgstr ""

#: nova/compute/disk.py:128
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#: nova/compute/disk.py:136
#, python-format
msgid "Failed to load partition: %s"
msgstr ""

#: nova/compute/disk.py:158
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: nova/compute/instance_types.py:41
#, python-format
msgid "Unknown instance type: %s"
msgstr ""

#: nova/compute/manager.py:69
#, python-format
msgid "check_instance_lock: decorating: |%s|"
msgstr ""

#: nova/compute/manager.py:71
#, python-format
msgid "check_instance_lock: arguments: |%s| |%s| |%s|"
msgstr ""

#: nova/compute/manager.py:75
#, python-format
msgid "check_instance_lock: locked: |%s|"
msgstr ""

#: nova/compute/manager.py:77
#, python-format
msgid "check_instance_lock: admin: |%s|"
msgstr ""

#: nova/compute/manager.py:82
#, python-format
msgid "check_instance_lock: executing: |%s|"
msgstr ""

#: nova/compute/manager.py:86
#, python-format
msgid "check_instance_lock: not executing |%s|"
msgstr ""

#: nova/compute/manager.py:157
msgid "Instance has already been created"
msgstr ""

#: nova/compute/manager.py:158
#, python-format
msgid "instance %s: starting..."
msgstr ""

#: nova/compute/manager.py:197
#, python-format
msgid "instance %s: Failed to spawn"
msgstr ""

#: nova/compute/manager.py:211 nova/tests/test_cloud.py:228
#, python-format
msgid "Terminating instance %s"
msgstr ""

#: nova/compute/manager.py:217
#, python-format
msgid "Disassociating address %s"
msgstr ""

#: nova/compute/manager.py:230
#, python-format
msgid "Deallocating address %s"
msgstr ""

#: nova/compute/manager.py:243
#, python-format
msgid "trying to destroy already destroyed instance: %s"
msgstr ""

#: nova/compute/manager.py:257
#, python-format
msgid "Rebooting instance %s"
msgstr ""

#: nova/compute/manager.py:260
#, python-format
msgid "trying to reboot a non-running instance: %s (state: %s excepted: %s)"
msgstr ""

#: nova/compute/manager.py:286
#, python-format
msgid "instance %s: snapshotting"
msgstr ""

#: nova/compute/manager.py:289
#, python-format
msgid ""
"trying to snapshot a non-running instance: %s (state: %s excepted: %s)"
msgstr ""

#: nova/compute/manager.py:301
#, python-format
msgid "instance %s: rescuing"
msgstr ""

#: nova/compute/manager.py:316
#, python-format
msgid "instance %s: unrescuing"
msgstr ""

#: nova/compute/manager.py:335
#, python-format
msgid "instance %s: pausing"
msgstr ""

#: nova/compute/manager.py:352
#, python-format
msgid "instance %s: unpausing"
msgstr ""

#: nova/compute/manager.py:369
#, python-format
msgid "instance %s: retrieving diagnostics"
msgstr ""

#: nova/compute/manager.py:382
#, python-format
msgid "instance %s: suspending"
msgstr ""

#: nova/compute/manager.py:401
#, python-format
msgid "instance %s: resuming"
msgstr ""

#: nova/compute/manager.py:420
#, python-format
msgid "instance %s: locking"
msgstr ""

#: nova/compute/manager.py:432
#, python-format
msgid "instance %s: unlocking"
msgstr ""

#: nova/compute/manager.py:442
#, python-format
msgid "instance %s: getting locked state"
msgstr ""

#: nova/compute/manager.py:462
#, python-format
msgid "instance %s: attaching volume %s to %s"
msgstr ""

#: nova/compute/manager.py:478
#, python-format
msgid "instance %s: attach failed %s, removing"
msgstr ""

#: nova/compute/manager.py:493
#, python-format
msgid "Detach volume %s from mountpoint %s on instance %s"
msgstr ""

#: nova/compute/manager.py:497
#, python-format
msgid "Detaching volume from unknown instance %s"
msgstr ""

#: nova/compute/monitor.py:259
#, python-format
msgid "updating %s..."
msgstr ""

#: nova/compute/monitor.py:289
msgid "unexpected error during update"
msgstr ""

#: nova/compute/monitor.py:355
#, python-format
msgid "Cannot get blockstats for \"%s\" on \"%s\""
msgstr ""

#: nova/compute/monitor.py:377
#, python-format
msgid "Cannot get ifstats for \"%s\" on \"%s\""
msgstr ""

#: nova/compute/monitor.py:412
msgid "unexpected exception getting connection"
msgstr ""

#: nova/compute/monitor.py:427
#, python-format
msgid "Found instance: %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:43
msgid "Use of empty request context is deprecated"
msgstr ""

#: nova/db/sqlalchemy/api.py:132
#, python-format
msgid "No service for id %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:229
#, python-format
msgid "No service for %s, %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:574
#, python-format
msgid "No floating ip for address %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:668
#, python-format
msgid "No instance for id %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:758 nova/virt/libvirt_conn.py:598
#: nova/virt/xenapi/volumeops.py:48 nova/virt/xenapi/volumeops.py:103
#, python-format
msgid "Instance %s not found"
msgstr ""

#: nova/db/sqlalchemy/api.py:891
#, python-format
msgid "no keypair for user %s, name %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1006 nova/db/sqlalchemy/api.py:1064
#, python-format
msgid "No network for id %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1036
#, python-format
msgid "No network for bridge %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1050
#, python-format
msgid "No network for instance %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1180
#, python-format
msgid "Token %s does not exist"
msgstr ""

#: nova/db/sqlalchemy/api.py:1205
#, python-format
msgid "No quota for project_id %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1356
#, python-format
msgid "No volume for id %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1401
#, python-format
msgid "Volume %s not found"
msgstr ""

#: nova/db/sqlalchemy/api.py:1413
#, python-format
msgid "No export device found for volume %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1426
#, python-format
msgid "No target id found for volume %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1471
#, python-format
msgid "No security group with id %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1488
#, python-format
msgid "No security group named %s for project: %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1576
#, python-format
msgid "No secuity group rule with id %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1650
#, python-format
msgid "No user for id %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1666
#, python-format
msgid "No user for access key %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:1728
#, python-format
msgid "No project with id %s"
msgstr ""

#: nova/image/glance.py:78
#, python-format
msgid "Parallax returned HTTP error %d from request for /images"
msgstr ""

#: nova/image/glance.py:97
#, python-format
msgid "Parallax returned HTTP error %d from request for /images/detail"
msgstr ""

#: nova/image/s3.py:82
#, python-format
msgid "Image %s could not be found"
msgstr ""

#: nova/network/api.py:39
#, python-format
msgid "Quota exceeeded for %s, tried to allocate address"
msgstr ""

#: nova/network/api.py:42
msgid "Address quota exceeded. You cannot allocate any more addresses"
msgstr ""

#: nova/network/linux_net.py:176
#, python-format
msgid "Starting VLAN inteface %s"
msgstr ""

#: nova/network/linux_net.py:186
#, python-format
msgid "Starting Bridge interface for %s"
msgstr ""

#: nova/network/linux_net.py:254
#, python-format
msgid "Hupping dnsmasq threw %s"
msgstr ""

#: nova/network/linux_net.py:256
#, python-format
msgid "Pid %d is stale, relaunching dnsmasq"
msgstr ""

#: nova/network/linux_net.py:334
#, python-format
msgid "Killing dnsmasq threw %s"
msgstr ""

#: nova/network/manager.py:135
msgid "setting network host"
msgstr ""

#: nova/network/manager.py:190
#, python-format
msgid "Leasing IP %s"
msgstr ""

#: nova/network/manager.py:194
#, python-format
msgid "IP %s leased that isn't associated"
msgstr ""

#: nova/network/manager.py:197
#, python-format
msgid "IP %s leased to bad mac %s vs %s"
msgstr ""

#: nova/network/manager.py:205
#, python-format
msgid "IP %s leased that was already deallocated"
msgstr ""

#: nova/network/manager.py:214
#, python-format
msgid "IP %s released that isn't associated"
msgstr ""

#: nova/network/manager.py:217
#, python-format
msgid "IP %s released from bad mac %s vs %s"
msgstr ""

#: nova/network/manager.py:220
#, python-format
msgid "IP %s released that was not leased"
msgstr ""

#: nova/network/manager.py:442
#, python-format
msgid "Dissassociated %s stale fixed ip(s)"
msgstr ""

#: nova/objectstore/handler.py:106
#, python-format
msgid "Unknown S3 value type %r"
msgstr ""

#: nova/objectstore/handler.py:137
msgid "Authenticated request"
msgstr ""

#: nova/objectstore/handler.py:182
msgid "List of buckets requested"
msgstr ""

#: nova/objectstore/handler.py:209
#, python-format
msgid "List keys for bucket %s"
msgstr ""

#: nova/objectstore/handler.py:217
#, python-format
msgid "Unauthorized attempt to access bucket %s"
msgstr ""

#: nova/objectstore/handler.py:235
#, python-format
msgid "Creating bucket %s"
msgstr ""

#: nova/objectstore/handler.py:245
#, python-format
msgid "Deleting bucket %s"
msgstr ""

#: nova/objectstore/handler.py:249
#, python-format
msgid "Unauthorized attempt to delete bucket %s"
msgstr ""

#: nova/objectstore/handler.py:271
#, python-format
msgid "Getting object: %s / %s"
msgstr ""

#: nova/objectstore/handler.py:274
#, python-format
msgid "Unauthorized attempt to get object %s from bucket %s"
msgstr ""

#: nova/objectstore/handler.py:292
#, python-format
msgid "Putting object: %s / %s"
msgstr ""

#: nova/objectstore/handler.py:295
#, python-format
msgid "Unauthorized attempt to upload object %s to bucket %s"
msgstr ""

#: nova/objectstore/handler.py:314
#, python-format
msgid "Deleting object: %s / %s"
msgstr ""

#: nova/objectstore/handler.py:393
#, python-format
msgid "Not authorized to upload image: invalid directory %s"
msgstr ""

#: nova/objectstore/handler.py:401
#, python-format
msgid "Not authorized to upload image: unauthorized bucket %s"
msgstr ""

#: nova/objectstore/handler.py:406
#, python-format
msgid "Starting image upload: %s"
msgstr ""

#: nova/objectstore/handler.py:420
#, python-format
msgid "Not authorized to update attributes of image %s"
msgstr ""

#: nova/objectstore/handler.py:428
#, python-format
msgid "Toggling publicity flag of image %s %r"
msgstr ""

#: nova/objectstore/handler.py:433
#, python-format
msgid "Updating user fields on image %s"
msgstr ""

#: nova/objectstore/handler.py:447
#, python-format
msgid "Unauthorized attempt to delete image %s"
msgstr ""

#: nova/objectstore/handler.py:452
#, python-format
msgid "Deleted image: %s"
msgstr ""

#: nova/scheduler/chance.py:37 nova/scheduler/simple.py:73
#: nova/scheduler/simple.py:106 nova/scheduler/simple.py:118
msgid "No hosts found"
msgstr ""

#: nova/scheduler/driver.py:66
msgid "Must implement a fallback schedule"
msgstr ""

#: nova/scheduler/manager.py:69
#, python-format
msgid "Casting to %s %s for %s"
msgstr ""

#: nova/scheduler/simple.py:63
msgid "All hosts have too many cores"
msgstr ""

#: nova/scheduler/simple.py:95
msgid "All hosts have too many gigabytes"
msgstr ""

#: nova/scheduler/simple.py:115
msgid "All hosts have too many networks"
msgstr ""

#: nova/tests/test_cloud.py:198
msgid "Can't test instances without a real virtual env."
msgstr ""

#: nova/tests/test_cloud.py:210
#, python-format
msgid "Need to watch instance %s until it's running..."
msgstr ""

#: nova/tests/test_compute.py:104
#, python-format
msgid "Running instances: %s"
msgstr ""

#: nova/tests/test_compute.py:110
#, python-format
msgid "After terminating instances: %s"
msgstr ""

#: nova/tests/test_rpc.py:89
#, python-format
msgid "Nested received %s, %s"
msgstr ""

#: nova/tests/test_rpc.py:94
#, python-format
msgid "Nested return %s"
msgstr ""

#: nova/tests/test_rpc.py:119 nova/tests/test_rpc.py:125
#, python-format
msgid "Received %s"
msgstr ""

#: nova/tests/test_volume.py:162
#, python-format
msgid "Target %s allocated"
msgstr ""

#: nova/virt/connection.py:73
msgid "Failed to open connection to the hypervisor"
msgstr ""

#: nova/virt/fake.py:210
#, python-format
msgid "Instance %s Not Found"
msgstr ""

#: nova/virt/hyperv.py:118
msgid "In init host"
msgstr ""

#: nova/virt/hyperv.py:131
#, python-format
msgid "Attempt to create duplicate vm %s"
msgstr ""

#: nova/virt/hyperv.py:148
#, python-format
msgid "Starting VM %s "
msgstr ""

#: nova/virt/hyperv.py:150
#, python-format
msgid "Started VM %s "
msgstr ""

#: nova/virt/hyperv.py:152
#, python-format
msgid "spawn vm failed: %s"
msgstr ""

#: nova/virt/hyperv.py:169
#, python-format
msgid "Failed to create VM %s"
msgstr ""

#: nova/virt/hyperv.py:171 nova/virt/xenapi/vm_utils.py:125
#, python-format
msgid "Created VM %s..."
msgstr ""

#: nova/virt/hyperv.py:188
#, python-format
msgid "Set memory for vm %s..."
msgstr ""

#: nova/virt/hyperv.py:198
#, python-format
msgid "Set vcpus for vm %s..."
msgstr ""

#: nova/virt/hyperv.py:202
#, python-format
msgid "Creating disk for %s by attaching disk file %s"
msgstr ""

#: nova/virt/hyperv.py:227
#, python-format
msgid "Failed to add diskdrive to VM %s"
msgstr ""

#: nova/virt/hyperv.py:230
#, python-format
msgid "New disk drive path is %s"
msgstr ""

#: nova/virt/hyperv.py:247
#, python-format
msgid "Failed to add vhd file to VM %s"
msgstr ""

#: nova/virt/hyperv.py:249
#, python-format
msgid "Created disk for %s"
msgstr ""

#: nova/virt/hyperv.py:253
#, python-format
msgid "Creating nic for %s "
msgstr ""

#: nova/virt/hyperv.py:272
msgid "Failed creating a port on the external vswitch"
msgstr ""

#: nova/virt/hyperv.py:273
#, python-format
msgid "Failed creating port for %s"
msgstr ""

#: nova/virt/hyperv.py:275
#, python-format
msgid "Created switch port %s on switch %s"
msgstr ""

#: nova/virt/hyperv.py:285
#, python-format
msgid "Failed to add nic to VM %s"
msgstr ""

#: nova/virt/hyperv.py:287
#, python-format
msgid "Created nic for %s "
msgstr ""

#: nova/virt/hyperv.py:320
#, python-format
msgid "WMI job failed: %s"
msgstr ""

#: nova/virt/hyperv.py:322
#, python-format
msgid "WMI job succeeded: %s, Elapsed=%s "
msgstr ""

#: nova/virt/hyperv.py:358
#, python-format
msgid "Got request to destroy vm %s"
msgstr ""

#: nova/virt/hyperv.py:383
#, python-format
msgid "Failed to destroy vm %s"
msgstr ""

#: nova/virt/hyperv.py:389
#, python-format
msgid "Del: disk %s vm %s"
msgstr ""

#: nova/virt/hyperv.py:405
#, python-format
msgid ""
"Got Info for vm %s: state=%s, mem=%s, num_cpu=%s,                     "
"cpu_time=%s"
msgstr ""

#: nova/virt/hyperv.py:424 nova/virt/xenapi/vm_utils.py:301
#, python-format
msgid "duplicate name found: %s"
msgstr ""

#: nova/virt/hyperv.py:444
#, python-format
msgid "Successfully changed vm state of %s to %s"
msgstr ""

#: nova/virt/hyperv.py:447 nova/virt/hyperv.py:449
#, python-format
msgid "Failed to change vm state of %s to %s"
msgstr ""

#: nova/virt/images.py:70
#, python-format
msgid "Finished retreving %s -- placed in %s"
msgstr ""

#: nova/virt/libvirt_conn.py:144
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: nova/virt/libvirt_conn.py:157
msgid "Connection to libvirt broke"
msgstr ""

#: nova/virt/libvirt_conn.py:229
#, python-format
msgid "instance %s: deleting instance files %s"
msgstr ""

#: nova/virt/libvirt_conn.py:271
#, python-format
msgid "No disk at %s"
msgstr ""

#: nova/virt/libvirt_conn.py:278
msgid "Instance snapshotting is not supported for libvirtat this time"
msgstr ""

#: nova/virt/libvirt_conn.py:294
#, python-format
msgid "instance %s: rebooted"
msgstr ""

#: nova/virt/libvirt_conn.py:297
#, python-format
msgid "_wait_for_reboot failed: %s"
msgstr ""

#: nova/virt/libvirt_conn.py:340
#, python-format
msgid "instance %s: rescued"
msgstr ""

#: nova/virt/libvirt_conn.py:343
#, python-format
msgid "_wait_for_rescue failed: %s"
msgstr ""

#: nova/virt/libvirt_conn.py:370
#, python-format
msgid "instance %s: is running"
msgstr ""

#: nova/virt/libvirt_conn.py:381
#, python-format
msgid "instance %s: booted"
msgstr ""

#: nova/virt/libvirt_conn.py:384 nova/virt/xenapi/vmops.py:116
#, python-format
msgid "instance %s: failed to boot"
msgstr ""

#: nova/virt/libvirt_conn.py:395
#, python-format
msgid "virsh said: %r"
msgstr ""

#: nova/virt/libvirt_conn.py:399
msgid "cool, it's a device"
msgstr ""

#: nova/virt/libvirt_conn.py:407
#, python-format
msgid "data: %r, fpath: %r"
msgstr ""

#: nova/virt/libvirt_conn.py:415
#, python-format
msgid "Contents of file %s: %r"
msgstr ""

#: nova/virt/libvirt_conn.py:449
#, python-format
msgid "instance %s: Creating image"
msgstr ""

#: nova/virt/libvirt_conn.py:505
#, python-format
msgid "instance %s: injecting key into image %s"
msgstr ""

#: nova/virt/libvirt_conn.py:508
#, python-format
msgid "instance %s: injecting net into image %s"
msgstr ""

#: nova/virt/libvirt_conn.py:516
#, python-format
msgid "instance %s: ignoring error injecting data into image %s (%s)"
msgstr ""

#: nova/virt/libvirt_conn.py:544 nova/virt/libvirt_conn.py:547
#, python-format
msgid "instance %s: starting toXML method"
msgstr ""

#: nova/virt/libvirt_conn.py:589
#, python-format
msgid "instance %s: finished toXML method"
msgstr ""

#: nova/virt/xenapi_conn.py:113
msgid ""
"Must specify xenapi_connection_url, xenapi_connection_username (optionally), "
"and xenapi_connection_password to use connection_type=xenapi"
msgstr ""

#: nova/virt/xenapi_conn.py:263
#, python-format
msgid "Task [%s] %s status: success    %s"
msgstr ""

#: nova/virt/xenapi_conn.py:271
#, python-format
msgid "Task [%s] %s status: %s    %s"
msgstr ""

#: nova/virt/xenapi_conn.py:287 nova/virt/xenapi_conn.py:300
#, python-format
msgid "Got exception: %s"
msgstr ""

#: nova/virt/xenapi/fake.py:72
#, python-format
msgid "%s: _db_content => %s"
msgstr ""

#: nova/virt/xenapi/fake.py:247 nova/virt/xenapi/fake.py:338
#: nova/virt/xenapi/fake.py:356 nova/virt/xenapi/fake.py:404
msgid "Raising NotImplemented"
msgstr ""

#: nova/virt/xenapi/fake.py:249
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr ""

#: nova/virt/xenapi/fake.py:283
#, python-format
msgid "Calling %s %s"
msgstr ""

#: nova/virt/xenapi/fake.py:288
#, python-format
msgid "Calling getter %s"
msgstr ""

#: nova/virt/xenapi/fake.py:340
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""

#: nova/virt/xenapi/network_utils.py:40
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:43
#, python-format
msgid "Found no network for bridge %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:127
#, python-format
msgid "Created VM %s as %s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:147
#, python-format
msgid "Creating VBD for VM %s, VDI %s ... "
msgstr ""

#: nova/virt/xenapi/vm_utils.py:149
#, python-format
msgid "Created VBD %s for VM %s, VDI %s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:165
#, python-format
msgid "VBD not found in instance %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:175
#, python-format
msgid "Unable to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:187
#, python-format
msgid "Unable to destroy VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:202
#, python-format
msgid "Creating VIF for VM %s, network %s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:205
#, python-format
msgid "Created VIF %s for VM %s, network %s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:216
#, python-format
msgid "Snapshotting VM %s with label '%s'..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:229
#, python-format
msgid "Created snapshot %s from VM %s."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:243
#, python-format
msgid "Asking xapi to upload %s as '%s'"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:261
#, python-format
msgid "Asking xapi to fetch %s as %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:279
#, python-format
msgid "Looking up vdi %s for PV kernel"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:290
#, python-format
msgid "PV Kernel in VDI:%d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:318
#, python-format
msgid "VDI %s is still available"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:331
#, python-format
msgid "(VM_UTILS) xenserver vm state -> |%s|"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:333
#, python-format
msgid "(VM_UTILS) xenapi power_state -> |%s|"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:390
#, python-format
msgid "VHD %s has parent %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:407
#, python-format
msgid "Re-scanning SR %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:431
#, python-format
msgid "Parent %s doesn't match original parent %s, waiting for coalesce..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:448
#, python-format
msgid "No VDIs found for VM %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:452
#, python-format
msgid "Unexpected number of VDIs (%s) found for VM %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:62
#, python-format
msgid "Attempted to create non-unique name %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:99
#, python-format
msgid "Starting VM %s..."
msgstr ""

#: nova/virt/xenapi/vmops.py:101
#, python-format
msgid "Spawning VM %s created %s."
msgstr ""

#: nova/virt/xenapi/vmops.py:112
#, python-format
msgid "Instance %s: booted"
msgstr ""

#: nova/virt/xenapi/vmops.py:137
#, python-format
msgid "Instance not present %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:166
#, python-format
msgid "Starting snapshot for VM %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:174
#, python-format
msgid "Unable to Snapshot %s: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:184
#, python-format
msgid "Finished snapshot and upload for VM %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:252
#, python-format
msgid "suspend: instance not present %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:262
#, python-format
msgid "resume: instance not present %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:271
#, python-format
msgid "Instance not found %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:57
#, python-format
msgid "Introducing %s..."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:74
#, python-format
msgid "Introduced %s as %s."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:78
msgid "Unable to create Storage Repository"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:90
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:96
#, python-format
msgid "Forgetting SR %s ... "
msgstr ""

#: nova/virt/xenapi/volume_utils.py:101
#, python-format
msgid "Ignoring exception %s when getting PBDs for %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:107
#, python-format
msgid "Ignoring exception %s when unplugging PBD %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:111
#, python-format
msgid "Forgetting SR %s done."
msgstr ""

#: nova/virt/xenapi/volume_utils.py:113
#, python-format
msgid "Ignoring exception %s when forgetting SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:123
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:128
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:146
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:175
#, python-format
msgid "Unable to obtain target information %s, %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:197
#, python-format
msgid "Mountpoint cannot be translated: %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:51
#, python-format
msgid "Attach_volume: %s, %s, %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:69
#, python-format
msgid "Unable to create VDI on SR %s for instance %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:81
#, python-format
msgid "Unable to use SR %s for instance %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:93
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:95
#, python-format
msgid "Mountpoint %s attached to instance %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:106
#, python-format
msgid "Detach_volume: %s, %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:113
#, python-format
msgid "Unable to locate volume %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:121
#, python-format
msgid "Unable to detach volume %s"
msgstr ""

#: nova/virt/xenapi/volumeops.py:128
#, python-format
msgid "Mountpoint %s detached from instance %s"
msgstr ""

#: nova/volume/api.py:44
#, python-format
msgid "Quota exceeeded for %s, tried to create %sG volume"
msgstr ""

#: nova/volume/api.py:46
#, python-format
msgid "Volume quota exceeded. You cannot create a volume of size %s"
msgstr ""

#: nova/volume/api.py:70 nova/volume/api.py:95
msgid "Volume status must be available"
msgstr ""

#: nova/volume/api.py:97
msgid "Volume is already attached"
msgstr ""

#: nova/volume/api.py:103
msgid "Volume is already detached"
msgstr ""

#: nova/volume/driver.py:76
#, python-format
msgid "Recovering from a failed execute.  Try number %s"
msgstr ""

#: nova/volume/driver.py:85
#, python-format
msgid "volume group %s doesn't exist"
msgstr ""

#: nova/volume/driver.py:210
#, python-format
msgid "FAKE AOE: %s"
msgstr ""

#: nova/volume/driver.py:315
#, python-format
msgid "FAKE ISCSI: %s"
msgstr ""

#: nova/volume/manager.py:85
#, python-format
msgid "Re-exporting %s volumes"
msgstr ""

#: nova/volume/manager.py:93
#, python-format
msgid "volume %s: creating"
msgstr ""

#: nova/volume/manager.py:102
#, python-format
msgid "volume %s: creating lv of size %sG"
msgstr ""

#: nova/volume/manager.py:106
#, python-format
msgid "volume %s: creating export"
msgstr ""

#: nova/volume/manager.py:113
#, python-format
msgid "volume %s: created successfully"
msgstr ""

#: nova/volume/manager.py:121
msgid "Volume is still attached"
msgstr ""

#: nova/volume/manager.py:123
msgid "Volume is not local to this node"
msgstr ""

#: nova/volume/manager.py:124
#, python-format
msgid "volume %s: removing export"
msgstr ""

#: nova/volume/manager.py:126
#, python-format
msgid "volume %s: deleting"
msgstr ""

#: nova/volume/manager.py:129
#, python-format
msgid "volume %s: deleted successfully"
msgstr "bind %s: slettet"
